C2DEVEL-16211: Index optimizations
C2Devel/ihashmap pull request #4
Opened 2024-09-18 12:27 UTC by Yurzs

2024-11-20 16:24 UTC, avderin requested changes

2024-11-20 16:24 UTC, avderin commented on ihashmap/cache.py
> +    def __new__(cls, protocol: CacheProtocol) -> Self:
а смысл тут в параметре protocol ?

2024-11-20 16:24 UTC, avderin commented on ihashmap/cache.py
> +            )
я понимаю, что key у нас тут для консистентности с get и delete, но жесткая привязка его к value[self.PRIMARY_KEY] делает ненужным этот параметр в этом и update-методе

2024-11-20 16:24 UTC, avderin commented on ihashmap/cache.py
> +                if matched_keys - {self.PRIMARY_KEY} or index.get_keys() == [self.PRIMARY_KEY]
Напиши тут коммент, что PK индекс есть у коллекции всегда.
И при PK-фильтрации поумолчанию используется он. 
Составные же с PK индексы получают приоритет (подменяют дефолтный PK-индекс) только если фильтрация затрагивает дополнительные (помимо PK) ключи этих индексов

2024-11-20 16:24 UTC, avderin commented on ihashmap/index.py
> +                isinstance(value, FunctionType) for value in subquery.values()
а можно пример функции в квери?

2024-11-20 16:24 UTC, avderin commented on ihashmap/index.py
> +                    {pk_key: pk, **index.cut_data(subquery)}
а смысл тут в cut_data, он и так уже приведен к полям индекса

2024-11-20 16:24 UTC, avderin commented on ihashmap/index.py
> +    def append(cls, cache_name, value: Mapping[str, Any]) -> None:
давай назовем entity вместо value, для консистентности с remove

2024-11-20 16:24 UTC, avderin commented on ihashmap/index.py
> +    def get_key(cls, value: Mapping[str, Any]) -> str:
давай gen_index_key  (потому что он его генерирует)

2024-11-20 16:24 UTC, avderin commented on ihashmap/index.py
> +    def keys_(cls, cache_name: str):
get_all_keys

ну и коммент, что это все значения ключа индекса
(вообще со словом "key" жуткая путаница, потому что ты ключами назвал поля целевой коллекции, может стоит переименовать свойство класса на fields и станет сразу лучше)

2024-11-20 16:24 UTC, avderin commented on ihashmap/index.py
> +    keys: List[str]
ну и коммент, что это названия полей в коллекции с данными

2024-11-20 16:24 UTC, avderin commented on ihashmap/index.py
> +                    for pk in index.get(cache_name, search_key, default=[])
вместо pk - pk_value
это же значение ключевого поля

2024-11-20 16:24 UTC, avderin commented on ihashmap/index.py
> +        pk_key = cls.cache().PRIMARY_KEY
pk_name, а то масло масляное

2024-11-20 16:24 UTC, avderin commented on ihashmap/index.py
> +                    {pk_key: pk, **index.cut_data(i)}
а зачем cut_data, это же index_data, т.е. уже приведенный к полям индекса набор

2024-11-20 16:24 UTC, avderin commented on ihashmap/index.py
> +                    for pk in index.get(cache_name, index.get_key(i), default=[])
pk_value

2024-11-20 16:24 UTC, avderin commented on ihashmap/index.py
> +        matches: List[Mapping[str, Any]] = []
а смысл ему быть листом мапингов, если все мапинги там имеют ключ cls.cache().PRIMARY_KEY, который PK целевой коллекции

кажется, что его можно заменить set-ом и не надо будет изгаляться со сложно понимаемой структурой combined_index ради дедупликации

2024-11-21 08:34 UTC, Yurzs commented on ihashmap/cache.py
> +    def __new__(cls, protocol: CacheProtocol) -> Self:
сигнатуры init и new должны совпадать

2024-11-21 09:18 UTC, Yurzs commented on ihashmap/cache.py
> +    def __new__(cls, protocol: CacheProtocol) -> Self:
`*args, **kwargs` тоже сойдет, сделаю так

2024-12-11 12:21 UTC, avderin commented on ihashmap/index.py
> +                    {pk_field: pk_value, **index.cut_data(subquery)}
тут можно написать **subquery

2024-12-11 12:21 UTC, avderin commented on ihashmap/index.py
> +                    {pk_field: pk_value, **index.cut_data(i)}
а смысл тут cut, если i взято из индекса, в котором оно и так "скачено"

2024-12-11 12:21 UTC, avderin commented on ihashmap/helpers.py
> +) -> List[Mapping[str, Any]]:
стоит переделать этот метод на bool

2024-12-11 13:09 UTC, avderin approved these changes

2024-12-18 12:26 UTC, merged